---
- name: Setup {{ project_name }} server in docker
  hosts: all

  vars_files:
    - vars/vars.yml 

  tasks:    
    - name: Create {{ project_name}} mount volume dir
      file:
        path: "{{ project_path }}/{{ mount_dir }}"
        state: directory
        owner: deploy
        group: deploy
        mode: 0755
      become: true
    
    - name: Copy docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ project_path }}/docker-compose.yml"

    - name: docker-compose down
      docker_compose:
        project_src: "{{ project_path }}/"
        state: absent
        remove_orphans: true
    
    - name: docker-compose up
      docker_compose:
        project_src: "{{ project_path }}/"
        build: false
        state: present
      register: output

    # - debug:
    #     var: output

    # - name: Test service is running
    #   assert:
    #     that: output.ansible_facts.gitlab-ce.{{ project_dir }}_gitlab-ce_1.state.running
