---
- name: Build {{ container_name }} jenkins slave
  hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  vars:
    build_image: false

  # Need to add jenkins to docker group
  tasks:
    - name: Build an image
      include_tasks: tasks/build.yml
      when: build_image
    
    - name: Run Container
      include_tasks: tasks/run.yml
    
