FROM {{ src_image }}

LABEL maintainer="lindynetech@gmail.com"

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get upgrade -y --no-install-recommends && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y apt-transport-https ca-certificates gnupg-agent software-properties-common && \
    DEBIAN_FRONTEND="noninteractive" apt-get install curl -y && \
    curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
    apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \ 
    apt-get install -y --no-install-recommends {{ package_list }} && \
    apt-get -q autoremove && \
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin && \
    mkdir -p /var/run/sshd

RUN groupadd -g {{ j_gid }} {{ j_user }} && \
    useradd -d /home/{{ j_user }} -s /bin/bash -m {{ j_user }} -u {{ j_uid }} -g {{ j_user }} && \
    echo {{ j_user }}:{{ j_password }} | chpasswd

EXPOSE 22

CMD ip route | grep "default via" | awk '{print $3}' && /usr/sbin/sshd -D
