---
- name: Build Ansible-ready lxd image with packer
  hosts: lxdservers

  vars_files:
    - vars/main.yml 

  vars:
    distros:
      - u1804
      
  tasks:

    - name: Override default user
      set_fact:
        username: "{{ ansible_user }}"
        public_key: /home/{{ ansible_user }}/.ssh/id_rsa
      when: username != ansible_user

    - name: Check if ssh key exists
      stat:
        path: "{{ public_key }}"
      register: key_status

    - name: Generate ssh keys
      openssh_keypair:
        path: "{{ public_key}}"
      when: not key_status.stat.exists

    - name: System Check
      include_tasks: system-check.yml    

    - name: Create temp dir
      tempfile:
        state: directory
        suffix: packer
        path: /tmp
      register: temp_dir

    - name: Set packer dir variable   
      set_fact:
        packer_dir: "{{ temp_dir.path }}"

    - name: Include tasks
      include_tasks: builds/{{ item }}/tasks.yml
      loop: "{{ distros }}"
        
    - name: Cleanup
      file:
        path: "{{ packer_dir }}"
        state: absent

    - command: lxc image ls -c L --format csv
      register: image_list

    # Will fail if bionic, focal as filename/distro mismatch
    - name: Run tests
      assert:
        that:
          - "{{ (tgt_img | lower) in image_list.stdout_lines }}"
        fail_msg: "Build status: Failed"
        success_msg: "Build status: OK"
      vars:
        tgt_img: "{{ item }}-{{image_prefix}}"
      loop: "{{ distros }}"

    - name: Report
      debug: 
        msg: All builds are complete
