---
- name: Build Ansible-ready lxd image with packer
  hosts: lxdservers

  vars_files:
    - vars/main.yml 

  tasks:   
    - name: Check lxd status
      command: lxd version
      register: lxd_status
      changed_when: false
      
    - name: No LXD installed
      fail:
        msg: Please install and init lxd
      when: lxd_status.rc != 0
    
    - name: Ensure packer is installed
      command: packer --version
      register: packer_status
     
    - name: No packer installed
      fail:
        msg: Please install packer
      when: packer_status.rc != 0
      
    - name: Create temp dir
      tempfile:
        state: directory
        suffix: packer
        path: /tmp
      register: temp_dir

    - name: Set packer dir variable   
      set_fact:
        packer_dir: "{{ temp_dir.path }}"

    - name: Include tasks
      include_tasks: builds/{{ item }}/tasks.yml
      loop:
        - debian10

    - name: Cleanup
      file:
        path: "{{ packer_dir }}"
        state: absent

    # - name: Run tests
    #   assert:
    #     that:
    #       - "{{ lxc image info centos7-ansible-agent }}"
    #     fail_msg: "Build status: Failed"
    #     success_msg: "Build status: OK"

    - name: Report
      debug: 
        msg: All builds are complete