---
- name: Add libcontainers repository
  get_url:
    url: "{{ crio_yum_libcontainers_repo }}"
    dest: '/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo'
    owner: root
    group: root
    mode: 0644

- name: Add crio repository
  get_url:
    url: "{{ crio_yum_repo }}"
    dest: '/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_k8s_version }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Install crio
  yum:
    name: cri-o
    state: present

- name: systemctl start crio
  systemd:
    name: crio
    state: started
    enabled: yes
    daemon_reload: yes
