Vagrant.configure("2") do |config|
  config.vm.box = "local/centos8"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.synced_folder  ".", "/vagrant", disabled: true
  
  # CentOS 8
  config.vm.define "centos8" do |conf|
    conf.vm.hostname = 'centos8.example.com'
    conf.vm.network "private_network", ip: "192.168.4.200"
    conf.vm.provider "libvirt" do |l|
      l.memory = 2024
      l.cpus = 1
    end
  end
  # U2004
  config.vm.define "ubuntu2004" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    conf.vm.hostname = 'ubuntu2004.example.com'
    conf.vm.network "private_network", ip: "192.168.4.201"
    conf.vm.provider "libvirt" do |l|
      l.memory = 2024
      l.cpus = 1
    end
  end

end
