- name: Delete container
  docker_container:
    name: "{{ container_name }}"
    state: absent

- name: Run
  docker_container:
    name: "{{ container_name }}"
    image: "{{ target_image }}:{{ target_tag }}"
    ports:
      - "{{ host_port }}:22"
    restart: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

    